### ISSUE TITLE
How to help?

### ISSUE THREAD

**Issue by kukulich** [mikey0000/HA-Luba#1]
I would be happy to help with this integration. Is there something I could do?

**Comment by mikey0000** [comment]
Absolutely! Bluetooth integration is possible now, so take a, look at the pyluba project. You'd want to look at the Bluetooth side of things for now or in addition add MQTT for advanced users (as you need a rooted android phone to aquire credentials)

Something simple would be to scan for and connect to a Luba.

**Comment by kukulich** [comment]
I’ve already done 4 integration however no of them use bluetooth :) But I wil try.

**Comment by mikey0000** [comment]
You'll find me on discord in ha as well if you have questions
