### ISSUE TITLE
Questions Regarding Connectivity

### ISSUE THREAD

**Issue by mllockwood** [mikey0000/HA-Luba#11]
First off, thank you so much for starting this integration.  I have it setup and it's "working".  But, HA seems to connect and disconnect quite often from my Luba 2.  Is the only source of connectivity between HA and the Luba 2 via Bluetooth?  Or, does it also connect via IP to the mower and/or RTK?  I'm wondering if my connection issues are related to the mower getting close, and then too far away from, my ESP32 Bluetooth proxy.  Or, if having the mower and RTK on a separate VLAN from HA might be an issue?  Thanks!

**Comment by mikey0000** [comment]
At the moment it's Bluetooth, there is an issue somewhere, sometimes on second connect it sometimes fails. Not sure why, and doesn't happen consistently. We are working away at cloud / WiFi support but it's not easy.

8/06/2024 7:24:05 am Michael Lockwood ***@***.***>:

**Comment by mllockwood** [comment]
Outstanding!  And, thanks again for the work on this.

**Comment by lackr007** [comment]
Great work guys, loving this project! Can confirm the same behavior where all entities show unavailable then toggle back to valid values, the timing is very random. Using ESP32 with ESPHome Bluetooth proxy firmware, the ESP32 is 2 Ft from Luba 2 and 5 Ft from WIFI AP.
