### ISSUE TITLE
Mowing speed is wrong

### ISSUE THREAD

**Issue by ThorstenBoettler** [mikey0000/HA-Luba#12]
The mowing speed is shown to fast. must be divided by 10 

Speed is set to 0.3m/s but shown as 30m/s

<img width="442" alt="image" src="https://github.com/mikey0000/HA-Luba/assets/57589233/33a28d56-ee0e-49cd-8b2d-78918d5d2a78">

**Comment by mikey0000** [comment]
Thanks, will fix it shortly
