### ISSUE TITLE
Can't see integration after adding custom repository

### ISSUE THREAD

**Issue by Kansalis** [mikey0000/HA-Luba#20]
I added the custom integration URL in HACS & it seemed to accept it ok. Rebooted HA (several times) but the integration is not listed in the "Set up a new integration" window. I double checked the repo list; it's not there but also says it already exists when I try to add it. I received no errors or issues with restarts etc.

Any ideas what I can check/update to make it show up?

![image](https://github.com/mikey0000/HA-Luba/assets/38373647/c1287873-7cc3-41f6-9a15-758e9b44cb70)

**Comment by mikey0000** [comment]
You've missed the installation step

**Comment by Kansalis** [comment]
There is no HA-Luba visible anywhere in HACS, despite it saying the repo is already present, as per the screenshot. If it were properly connected, it would be visible in that list.

**Comment by mikey0000** [comment]
It's called mammotion

**Comment by Kansalis** [comment]
There's no mention of luba, mammotion, mikey0000 or any other search term I can think of in any HACS screen or the Add Integration window. Nothing I can find in the logs either. It seems as if the repo is not connected, but as the screenshot shows, HACS thinks it is as it won't let me add it.

**Comment by mikey0000** [comment]
Any chance you have visual studio code installed as an addon? Can you check the custom_components folder? At this point this is a problem with your HA /HACS and honestly I'm not sure what wrong, perhaps jump on our discord, will be a lot easier than trying to diagnose your issue here.

**Comment by veshapidze** [comment]
Same issue. Nothing comes up under "mammotion", "ha-luba", or "Luba"

**Comment by veshapidze** [comment]
Solved by adding custom integration https://github.com/mikey0000/HA-Luba
