### ISSUE TITLE
How to Set up?

### ISSUE THREAD

**Issue by TheRealSimon42** [mikey0000/HA-Luba#3]
Hey there,
first of all, thank you for you amazing work so far 💙

I just was curious if this integration is working and added it to HACS. Currently, it seems like, there are no fields displayed when trying to set up the integration. 

![Google Chrome - Einstellungen – Home Assistant_2024-05-28_23 48 14@2x](https://github.com/mikey0000/HA-Luba/assets/62359912/42624813-2884-412a-aba7-b75f0451f000)

Am I maybe missing some requirement, or is the YAML-Configuration currently the one expected to use? If yes, what should it look like?

**Comment by mikey0000** [comment]
Early days mate, I have a bug in pyluba I need to squish.

I'll be adding to this over the month. Will have plenty of additional sensors etc coming.

29/05/2024 9:51:07 am TheRealSimon42 ***@***.***>:

**Comment by mikey0000** [comment]
Also I broke it a little this morning repull it. Do you have a Luba 1 or 2?

Yes works in HACS and should find your Luba via Bluetooth

**Comment by driesvandamme** [comment]
Logger: homeassistant.config_entries
Bron: config_entries.py:2684
Eerst voorgekomen: 28 mei 2024 om 23:58:45 (2 gebeurtenissen)
Laatst gelogd: 00:04:51

Error occurred loading flow for integration luba: No module named 'my_pypi_package'

**Comment by TheRealSimon42** [comment]
> Also I broke it a little this morning repull it. Do you have a Luba 1 or 2?
> 
> Yes works in HACS and should find your Luba via Bluetooth

Thank you. I pulled it 60 minutes ago or so. I'll try to add a Bluetooth-Proxy near to my Luba2 and see what it does 🙌

**Comment by ThorstenBoettler** [comment]
@TheRealSimon42 how did you solved the problem with "Nicht alle Pflichtfelder sind ausgefüllt." ?

**Comment by mikey0000** [comment]
I don't get that issue. I suspect no Luba has been found.

**Comment by ThorstenBoettler** [comment]
@mikey0000 solved the problem, bluetooth proxy was not connected to HA

**Comment by mikey0000** [comment]
Pushed a few fixes, try and pull it now
