### ISSUE TITLE
Unable to configure the integration

### ISSUE THREAD

**Issue by InToSSH** [mikey0000/HA-Luba#8]
Hi,
I downloaded the integration using HACS, but I am unable to set up the integration using config flow.

I get an error `Config flow could not be loaded: {"message":"Invalid handler specified"}`
Other times it just keeps loading and nothing happens.

I am using HA supervised 2024.5.5
The BT should be working via BT proxy on Shelly Gen2 device.

Is there more troubleshooting I can do?

Thank you

![2024-06-04_00-31](https://github.com/mikey0000/HA-Luba/assets/6452373/111dfb40-0510-4fcc-8fdb-2c891540d1de)
![2024-06-04_00-33](https://github.com/mikey0000/HA-Luba/assets/6452373/b52f5870-26d5-4aff-9b27-b061c709f6ae)

**Comment by mikey0000** [comment]
Can you go to your logs and see what the error is please and paste here, thanks

**Comment by mikey0000** [comment]
Chances are your bluetooth is too far away from the mower. Can you also tell me if you have a Luba 1/2 ?

**Comment by InToSSH** [comment]
Thanks for the response, I found these two log entries:
```
This error originated from a custom integration.

Logger: py.warnings
Source: custom_components/mammotion/__init__.py:14
integration: mammotion
First occurred: 1:01:21 AM (1 occurrences)
Last logged: 1:01:21 AM

/usr/local/lib/python3.12/site-packages/stringcase.py:247: SyntaxWarning: invalid escape sequence '\W' return re.sub("\W+", "", string)
```
```
Logger: homeassistant.config_entries
Source: config_entries.py:2684
First occurred: 12:48:29 AM (1 occurrences)
Last logged: 12:48:29 AM

Error occurred loading flow for integration mammotion: No module named 'pyluba'
```
Now that I tried it again, it doesn't show the error, however it shows empty popup with submit button.
Also I have Luba 2 and the Shelly BT proxy is about 5 meters away from the Luba.
![2024-06-04_01-04](https://github.com/mikey0000/HA-Luba/assets/6452373/500f8d4b-09c3-49e4-8561-a58307963405)

**Comment by mikey0000** [comment]
Yeah HACS can be a bit funny and not install dependencies. Looks like it finally installed, is your shelly setup to be an ACTIVE BLE proxy? Does it support active connections? make sure your shelly is listed in esphome in HA.

**Comment by mikey0000** [comment]
> The shelly BLE proxy can’t work in this situation, as they don’t proxy actual Bluetooth connections, they only support advertisements.

Time to get an esp32 or atom lite
https://community.home-assistant.io/t/shelly-plus-ble-no-devices-added-in-homeassistant/509199/21

**Comment by InToSSH** [comment]
Thank you. Good to know, I assumed since it supports active connection it would work. I will set up an ESP32 and give it a go.
